#!/bin/sh 
#****************************************************************
# Control WebTools  Start, Stop and report Status to Synology
#
# Actual downloading and installation is done in postinst (after the package is placed
# at its runtime location by Synology)
#
# Webtools is a Plex Media Server PlugIn
#
# Written by dane22, a Plex Community member
# Synology port by ChuckPa, a Plex Community member
#
# Ver:  28.Mar.2016  - Initial Synology script  CL   -- BETA TEST 
# Ver:  02.Apr.2016  - Augmented for final release CL 
# Ver:  23.Apr.2016  - Update to ver 1.2,  Support DSM 5.2 & 6.0 U3 
#                      Improve error message in log if WebTools corrupt/missing
#****************************************************************
#
# Support functions first
#
######################################################################
# Put error messages in appropriate system log / communicate back to user

WriteLog() {

    touch       "$LOGFILE"
    echo `date +"%Y-%m-%e %H.%M.%S %Z"`: $*  >> "$LOGFILE"

}


GetDestination() {

  # On Synology,  the Pre-install script will have been run to determine if Plex is
  # installed.  It will error if not.

  PMS_DIR="`synoshare --get Plex | grep Path | awk -F\[ '{ print $2 }' \
                                               | awk -F\] '{ print $1 }'`"

  # Now build the Plug-in directory

  PLUGIN_DIR="$PMS_DIR/Library/Application Support/Plex Media Server/Plug-ins"

  # The Logfile (just in case)
  LOGFILE="$PLUGIN_DIR/WebTools.log"


}

#################################### Main Routine ########################################


  # Setup for the proper destination
  GetDestination


# IsLoaded ($Plugin-Dir/.isloaded) is present after successful download & unpack
# IsRunning ($Plugin-Dir/.isrunning) is state flag to make machines like Synology happy

  IsLoaded=0
  IsRunning=0

  # Is WebTools loaded on this system
  if [ -f "$PLUGIN_DIR/WebTools.bundle/.isloaded" ]; then
    IsLoaded=1
  fi

  # Is WebTools currently 'running' based on host 'start/stop' commands.
  # (independent of what Plex actually does with it)
  if [ -f "$PLUGIN_DIR/WebTools.bundle/.isrunning" ]; then
    IsRunning=1
  fi


# What were we asked to do
  case "$1" in
  start)

    WriteLog "Started"

    # Only do this if not 'loaded' (download and extract)
    if [ $IsLoaded -eq 0 ]; then 
      # Can't start, not installed/loaded correctly (must cleanup manually & retry)
      WriteLog "ERROR: DSM says WebTools loaded but it is not loaded"
      exit 1
    fi

    # Now mark it as running

    touch "$PLUGIN_DIR/WebTools.bundle/.isrunning"

    # Create the DSM shortcut (Puts the icon on the menu)
    if [ ! -f "/usr/syno/synoman/webman/3rdparty/WebTools" ]; then
      ln -s "/var/packages/WebTools/target/dsm_config/WebTools" /usr/syno/synoman/webman/3rdparty
    fi
      
    exit 0
    ;;

  stop)
    

    WriteLog "Stopped"


    rm -f "$PLUGIN_DIR/WebTools.bundle/.isrunning"

    # Remove the Start Menu link
    rm -f /usr/syno/synoman/webman/3rdparty/WebTools

    exit 0    # Synology now 'Not Running'
    ;;

  status)

    if [ $IsRunning -eq 1 ]; then
      exit 0;

    fi

    # Not Running
    exit 1;


    ;;
 
  restart)
    $0 stop

    $0 start
    exit $?
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit 0
